{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "ab6fac79_a2a038e2",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1000103
      },
      "writtenOn": "2021-11-08T11:26:29Z",
      "side": 1,
      "message": "We haven\u0027t been able to test fully yet, but on first examination looks good. ",
      "revId": "adf450663e6d2956cea62be7429f518a29230752",
      "serverId": "84e4e190-e623-4c37-9eda-58b1937c1b53"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "21e022d2_36f5bd32",
        "filename": "dmaapadapter/adapter/code/consumer.py",
        "patchSetId": 3
      },
      "lineNbr": 62,
      "author": {
        "id": 1000128
      },
      "writtenOn": "2021-11-10T09:52:14Z",
      "side": 1,
      "message": "dubug -\u003e debug\n\nThis gives the following error:\nDEBUG - Failed to get event information due to unexpected reason! \u0027RootLogger\u0027 object has no attribute \u0027dubug\u0027\n\nI fixed this bug and tried again. Now, I see this error:\nDEBUG - Error reading message : KafkaError{code\u003dUNKNOWN_TOPIC_OR_PART,val\u003d3,str\u003d\"Subscribed topic not available: unauthenticated.SEC_FAULT_OUTPUT: Broker: Unknown topic or partition\"}\n\nI am wondering how would you create a new topic?\nDoes the topic need to be created directly in Kafka, and this dmaap adapter would just read the messages from different topics?\n\nAs a sidenote, even though the above calls fail, the dmaap adapter still returns 200 which also seems to be a bug:\nINFO - 172.22.0.1 - - [10/Nov/2021 09:41:01] \"GET /dmaapapi/v1/events/unauthenticated.SEC_FAULT_OUTPUT/testGroup/testId HTTP/1.1\" 200",
      "revId": "adf450663e6d2956cea62be7429f518a29230752",
      "serverId": "84e4e190-e623-4c37-9eda-58b1937c1b53"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "c075ccc7_a349d055",
        "filename": "dmaapadapter/adapter/code/consumer.py",
        "patchSetId": 3
      },
      "lineNbr": 62,
      "author": {
        "id": 1001000
      },
      "writtenOn": "2021-11-10T11:09:42Z",
      "side": 1,
      "message": "We are aware about the typo. We will rectify \"dubug\" in next commit.\n\nCurrently we are developing the consumer side. It will just read messages from the topic.\n\nYes you are right. We have plan to enhance DMaaP adapter to return error message along with error code as response.",
      "parentUuid": "21e022d2_36f5bd32",
      "revId": "adf450663e6d2956cea62be7429f518a29230752",
      "serverId": "84e4e190-e623-4c37-9eda-58b1937c1b53"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "e245907a_88e4343e",
        "filename": "dmaapadapter/adapter/code/consumer.py",
        "patchSetId": 3
      },
      "lineNbr": 62,
      "author": {
        "id": 1001000
      },
      "writtenOn": "2021-11-10T11:42:04Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "c075ccc7_a349d055",
      "revId": "adf450663e6d2956cea62be7429f518a29230752",
      "serverId": "84e4e190-e623-4c37-9eda-58b1937c1b53"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "0370760f_5e6c5397",
        "filename": "dmaapadapter/adapter/code/consumer.py",
        "patchSetId": 3
      },
      "lineNbr": 62,
      "author": {
        "id": 1000128
      },
      "writtenOn": "2021-11-10T14:36:47Z",
      "side": 1,
      "message": "Thanks for your reply.\n\nI am still facing some problem in reading the message using dmaapadapter. I might be doing something wrong here, but it would be good if you can double check. I am following these steps:\n\n1) create topic:\ndocker exec smo-kafka sh -c \"kafka-topics --create --zookeeper smo-zookeeper:22181 --replication-factor 1 --partitions 1 --topic unauthenticated.SEC_FAULT_OUTPUT\"\n\n2) check created topic using dmaapadapter:\n$curl http://localhost:5000/dmaapapi/v1/topics\n{\"topics\": [\"unauthenticated.SEC_FAULT_OUTPUT\", \"__confluent.support.metrics\", \"__consumer_offsets\"]}\n\n3) write a message to the topic:\ndocker exec smo-kafka sh -c \"echo \u0027Hello, World\u0027 | kafka-console-producer --broker-list smo-kafka:29092 --topic unauthenticated.SEC_FAULT_OUTPUT\"\n\n4) read the message using dmaapadapter:\n$curl http://localhost:5000/dmaapapi/v1/events/unauthenticated.SEC_FAULT_OUTPUT/testGroup/testId\n[]\n\nThe message list is empty. These are the logs appearing in dmaapadapter:\n172.25.0.1 - - [10/Nov/2021 14:20:00] \"GET /dmaapapi/v1/events/unauthenticated.SEC_FAULT_OUTPUT/testGroup/testId HTTP/1.1\" 200 -\ntopic\u003dunauthenticated.SEC_FAULT_OUTPUT, consumergroup\u003dtestGroup, consumerid\u003dtestId, limit\u003d-1, timeout\u003d15 \n2021-11-10 14:20:00.%f +0000 root - DEBUG - No records \n2021-11-10 14:20:00.%f +0000 root - DEBUG - closing consumer\n2021-11-10 14:20:00.%f +0000 werkzeug - INFO - 172.25.0.1 - - [10/Nov/2021 14:20:00] \"GET /dmaapapi/v1/events/unauthenticated.SEC_FAULT_OUTPUT/testGroup/testId HTTP/1.1\" 200 -\n\n\nI can read the message directly from Kafka if I don\u0027t use the dmaapadapter:\ndocker exec smo-kafka sh -c \"kafka-console-consumer --bootstrap-server smo-kafka:29092 --topic unauthenticated.SEC_FAULT_OUTPUT --from-beginning\"\nHello, World",
      "parentUuid": "e245907a_88e4343e",
      "revId": "adf450663e6d2956cea62be7429f518a29230752",
      "serverId": "84e4e190-e623-4c37-9eda-58b1937c1b53"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "ee043bcf_e111248d",
        "filename": "dmaapadapter/adapter/code/consumer.py",
        "patchSetId": 3
      },
      "lineNbr": 62,
      "author": {
        "id": 1001000
      },
      "writtenOn": "2021-11-12T10:26:48Z",
      "side": 1,
      "message": "Please take latest code and and try. This problem is resolved.",
      "parentUuid": "0370760f_5e6c5397",
      "revId": "adf450663e6d2956cea62be7429f518a29230752",
      "serverId": "84e4e190-e623-4c37-9eda-58b1937c1b53"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "b9389429_896e347f",
        "filename": "dmaapadapter/adapter/code/consumer.py",
        "patchSetId": 3
      },
      "lineNbr": 62,
      "author": {
        "id": 1000128
      },
      "writtenOn": "2021-11-12T12:28:36Z",
      "side": 1,
      "message": "Thanks, it works now.",
      "parentUuid": "ee043bcf_e111248d",
      "revId": "adf450663e6d2956cea62be7429f518a29230752",
      "serverId": "84e4e190-e623-4c37-9eda-58b1937c1b53"
    }
  ]
}